-- VHDL Entity echo_lib.audio_io_v2.symbol
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-116.ad.liu.se)
--          at - 22:23:54 10/30/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY audio_io_v2 IS
   PORT( 
      AUD_ADCDAT        : IN     std_logic;
      c0                : IN     STD_LOGIC;
      data_valid        : IN     std_logic;
      fpga_reset        : IN     std_logic;
      left_channel_out  : IN     std_logic_vector (15 DOWNTO 0);
      right_channel_out : IN     std_logic_vector (15 DOWNTO 0);
      AUD_ADCLRCK       : OUT    std_logic;
      AUD_BCLK          : OUT    std_logic;
      AUD_DACDAT        : OUT    std_logic;
      AUD_DACLRCK       : OUT    std_logic;
      AUD_XCK           : OUT    std_logic;
      audio_in_left     : OUT    std_logic_vector (15 DOWNTO 0);
      audio_in_right    : OUT    std_logic_vector (15 DOWNTO 0);
      in_valid          : OUT    std_logic
   );

-- Declarations

END audio_io_v2 ;

--
-- VHDL Architecture echo_lib.audio_io_v2.struct
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-116.ad.liu.se)
--          at - 22:23:54 10/30/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY echo_lib;

ARCHITECTURE struct OF audio_io_v2 IS

   -- Architecture declarations

   -- Internal signal declarations

   -- Implicit buffer signal declarations
   SIGNAL AUD_BCLK_internal : std_logic;
   SIGNAL AUD_XCK_internal  : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'clkdiv'
   SIGNAL mw_U_1reg_cval : INTEGER RANGE 0 TO 3;
   SIGNAL mw_U_1reg_nval : INTEGER RANGE 0 TO 3;

   -- Component Declarations
   COMPONENT adc2parallel
   PORT (
      AUD_ADCDAT     : IN     std_logic ;
      c0             : IN     STD_LOGIC ;
      fpga_reset     : IN     std_logic ;
      audio_in_left  : OUT    std_logic_vector (15 DOWNTO 0);
      audio_in_right : OUT    std_logic_vector (15 DOWNTO 0);
      in_valid       : OUT    std_logic ;
      AUD_XCK        : IN     std_logic ;
      AUD_BCLK       : IN     std_logic ;
      AUD_ADCLRCK    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT dithered_clk_divider
   PORT (
      c0         : IN     STD_LOGIC ;
      fpga_reset : IN     std_logic ;
      AUD_XCK    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT parallel2dac
   PORT (
      AUD_BCLK          : IN     std_logic ;
      AUD_XCK           : IN     std_logic ;
      c0                : IN     STD_LOGIC ;
      data_valid        : IN     std_logic ;
      fpga_reset        : IN     std_logic ;
      left_channel_out  : IN     std_logic_vector (15 DOWNTO 0);
      right_channel_out : IN     std_logic_vector (15 DOWNTO 0);
      AUD_DACDAT        : OUT    std_logic ;
      AUD_DACLRCK       : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : adc2parallel USE ENTITY echo_lib.adc2parallel;
   FOR ALL : dithered_clk_divider USE ENTITY echo_lib.dithered_clk_divider;
   FOR ALL : parallel2dac USE ENTITY echo_lib.parallel2dac;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'clkdiv'
   u_1drive_proc: PROCESS (mw_U_1reg_cval)
   BEGIN
      IF (mw_U_1reg_cval >= 2) THEN
         AUD_BCLK_internal <= '1';
      ELSE
         AUD_BCLK_internal <= '0';
      END IF;
   END PROCESS u_1drive_proc;
   u_1clk_in_proc: PROCESS (AUD_XCK_internal)
   BEGIN
      IF (AUD_XCK_internal'EVENT AND AUD_XCK_internal='1') THEN
         mw_U_1reg_cval <= mw_U_1reg_nval;
      END IF;
   END PROCESS u_1clk_in_proc;
   u_1combo_proc: PROCESS (mw_U_1reg_cval, fpga_reset)
   BEGIN
      IF (fpga_reset = '0') THEN
         mw_U_1reg_nval <= 0;
      ELSIF (mw_U_1reg_cval = 3) THEN
         mw_U_1reg_nval <= 0;
      ELSE
         mw_U_1reg_nval <= mw_U_1reg_cval + 1;
      END IF;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.
   U_2 : adc2parallel
      PORT MAP (
         AUD_ADCDAT     => AUD_ADCDAT,
         c0             => c0,
         fpga_reset     => fpga_reset,
         audio_in_left  => audio_in_left,
         audio_in_right => audio_in_right,
         in_valid       => in_valid,
         AUD_XCK        => AUD_XCK_internal,
         AUD_BCLK       => AUD_BCLK_internal,
         AUD_ADCLRCK    => AUD_ADCLRCK
      );
   U_4 : dithered_clk_divider
      PORT MAP (
         c0         => c0,
         fpga_reset => fpga_reset,
         AUD_XCK    => AUD_XCK_internal
      );
   U_3 : parallel2dac
      PORT MAP (
         AUD_BCLK          => AUD_BCLK_internal,
         AUD_XCK           => AUD_XCK_internal,
         c0                => c0,
         data_valid        => data_valid,
         fpga_reset        => fpga_reset,
         left_channel_out  => left_channel_out,
         right_channel_out => right_channel_out,
         AUD_DACDAT        => AUD_DACDAT,
         AUD_DACLRCK       => AUD_DACLRCK
      );

   -- Implicit buffered output assignments
   AUD_BCLK <= AUD_BCLK_internal;
   AUD_XCK  <= AUD_XCK_internal;

END struct;
