-- VHDL Entity echo_lib.audio_io.generatedInstance
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-109.ad.liu.se)
--          at - 16:53:03 10/23/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY audio_io IS
   PORT( 
      clk        : IN     std_logic;
      data_ready : IN     std_logic;
      data_valid : OUT    std_logic;
      i2s_adcdat : IN     std_logic;
      i2s_bclk   : IN     std_logic;
      i2s_dacdat : OUT    std_logic;
      i2s_lrclk  : IN     std_logic;
      left_in    : OUT    std_logic_vector (15 DOWNTO 0);
      left_out   : IN     std_logic_vector (15 DOWNTO 0);
      mclk       : OUT    std_logic;
      mclk_in    : IN     std_logic;
      right_in   : OUT    std_logic_vector (15 DOWNTO 0);
      right_out  : IN     std_logic_vector (15 DOWNTO 0);
      rst        : IN     std_logic
   );

END audio_io ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF audio_io IS 
BEGIN


END generatedInstance;
