-- VHDL Entity echo_lib.color_mixer.symbol
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-112.ad.liu.se)
--          at - 21:52:53 10/06/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY color_mixer IS
   PORT( 
      b_in_0 : IN     std_logic_vector (7 DOWNTO 0);
      b_in_1 : IN     std_logic_vector (7 DOWNTO 0);
      g_in_0 : IN     std_logic_vector (7 DOWNTO 0);
      g_in_1 : IN     std_logic_vector (7 DOWNTO 0);
      r_in_0 : IN     std_logic_vector (7 DOWNTO 0);
      r_in_1 : IN     std_logic_vector (7 DOWNTO 0);
      sel    : IN     std_logic;
      b_out  : OUT    std_logic_vector (7 DOWNTO 0);
      g_out  : OUT    std_logic_vector (7 DOWNTO 0);
      r_out  : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END color_mixer ;

--
-- VHDL Architecture echo_lib.color_mixer.struct
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-112.ad.liu.se)
--          at - 21:52:53 10/06/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ARCHITECTURE struct OF color_mixer IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'blue' of 'mux'
   bluecombo_proc: PROCESS(b_in_0, b_in_1, sel)
   BEGIN
      CASE sel IS
         WHEN '0' => b_out <= b_in_0;
         WHEN '1' => b_out <= b_in_1;
         WHEN OTHERS => b_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS bluecombo_proc;

   -- ModuleWare code(v1.12) for instance 'green' of 'mux'
   greencombo_proc: PROCESS(g_in_0, g_in_1, sel)
   BEGIN
      CASE sel IS
         WHEN '0' => g_out <= g_in_0;
         WHEN '1' => g_out <= g_in_1;
         WHEN OTHERS => g_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS greencombo_proc;

   -- ModuleWare code(v1.12) for instance 'red' of 'mux'
   redcombo_proc: PROCESS(r_in_0, r_in_1, sel)
   BEGIN
      CASE sel IS
         WHEN '0' => r_out <= r_in_0;
         WHEN '1' => r_out <= r_in_1;
         WHEN OTHERS => r_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS redcombo_proc;

   -- Instance port mappings.

END struct;
