-- VHDL Entity echo_lib.echo.symbol
--
-- Created:
--          by - alfth698.student-liu.se (muxen2-109.ad.liu.se)
--          at - 17:23:54 10/28/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY echo IS
   GENERIC( 
      G_ADDR_WIDTH    : natural := 20;         --2^20 x 16 = 2 MB
      G_DATA_WIDTH    : natural := 16;         --Audio 16-bit
      G_FS_HZ         : natural := 44100;      --samplerate
      G_GAIN_INIT_Q15 : natural := 9830;       --~0.30 (0.30 * 32768)
      G_GAIN_STEP_Q15 : natural := 512;        --~0.015625 per keyboard use
      G_DELAY_INIT_MS : natural := 1000;       --1.00 s Start
      G_DELAY_STEP_MS : natural := 100         --100 ms per keyboard use
   );
   PORT( 
      KB_SCAN_CODE    : IN     std_logic_vector (7 DOWNTO 0);
      RESET_N         : IN     std_logic;
      audio_in_L      : IN     std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_in_R      : IN     std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_in_valid  : IN     std_logic;
      clk             : IN     std_logic;
      SRAM_ADDR       : OUT    std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      SRAM_CE_N       : OUT    std_logic;
      SRAM_LB_N       : OUT    std_logic;
      SRAM_OE_N       : OUT    std_logic;
      SRAM_UB_N       : OUT    std_logic;
      SRAM_WE_N       : OUT    std_logic;
      audio_in_ready  : OUT    std_logic;
      audio_out_L     : OUT    std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_out_R     : OUT    std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_out_valid : OUT    std_logic;
      delay_samples   : OUT    std_logic_vector (18 DOWNTO 0);
      g_feedback_q15  : OUT    std_logic_vector (15 DOWNTO 0);
      SRAM_DQ         : INOUT  std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0)
   );

-- Declarations

END echo ;

--
-- VHDL Architecture echo_lib.echo.struct
--
-- Created:
--          by - alfth698.student-liu.se (muxen2-109.ad.liu.se)
--          at - 17:27:27 10/28/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY echo_lib;
USE echo_lib.keyboard_package.ALL;


ARCHITECTURE struct OF echo IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ctrl_sig     : std_logic_vector(5 DOWNTO 0);
   SIGNAL echo_disable : std_logic;
   SIGNAL rd_addr      : std_logic_vector(G_ADDR_WIDTH-1 DOWNTO 0);
   SIGNAL rd_data      : std_logic_vector(G_DATA_WIDTH-1 DOWNTO 0);
   SIGNAL rd_en        : std_logic;
   SIGNAL rd_valid     : std_logic;
   SIGNAL wr_addr      : std_logic_vector(G_ADDR_WIDTH-1 DOWNTO 0);
   SIGNAL wr_data      : std_logic_vector(G_DATA_WIDTH-1 DOWNTO 0);
   SIGNAL wr_en        : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL delay_samples_internal  : std_logic_vector (18 DOWNTO 0);
   SIGNAL g_feedback_q15_internal : std_logic_vector (15 DOWNTO 0);


   -- Component Declarations
   COMPONENT echo_logic
   GENERIC (
      G_ADDR_WIDTH : natural := 20;      -- physische Adressbreite
      G_DATA_WIDTH : natural := 16
   );
   PORT (
      clk             : IN     std_logic ;
      RESET_N         : IN     std_logic ;
      audio_in_L      : IN     std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_in_R      : IN     std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_out_L     : OUT    std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_out_R     : OUT    std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_in_ready  : OUT    std_logic ;
      audio_in_valid  : IN     std_logic ;
      audio_out_valid : OUT    std_logic ;
      wr_en           : OUT    std_logic ;
      wr_addr         : OUT    std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      wr_data         : OUT    std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      rd_en           : OUT    std_logic ;
      rd_addr         : OUT    std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      rd_valid        : IN     std_logic ;
      rd_data         : IN     std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      echo_disable    : IN     std_logic ;
      g_feedback_q15  : IN     std_logic_vector (15 DOWNTO 0);
      delay_samples   : IN     std_logic_vector (18 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT gen_kb_dec
   GENERIC (
      N       : integer := 18;               -- Number of functions
      key_map : key_array(N-1 downto 0)      -- Key map provided by user
   );
   PORT (
      clk           : IN     std_logic;
      scancode      : IN     std_logic_vector (7 DOWNTO 0);
      invalid_led   : OUT    std_logic;
      output_signal : OUT    std_logic_vector (N-1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT gen_para
   GENERIC (
      fs_hz         : positive := 44100;      -- Sampling frequency
      step_delay_ms : natural  := 250;        -- 0,25 s
      step_gain_q15 : natural  := 1638        -- ?0,05
   );
   PORT (
      RESET_N        : IN     std_logic ;
      clk            : IN     std_logic ;
      ctrl_sig       : IN     std_logic_vector (5 DOWNTO 0);
      delay_samples  : OUT    std_logic_vector (18 DOWNTO 0);
      echo_disable   : OUT    std_logic ;
      g_feedback_q15 : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT sram_ctrl
   GENERIC (
      G_ADDR_WIDTH : natural := 20;
      G_DATA_WIDTH : natural := 16
   );
   PORT (
      rd_valid  : OUT    std_logic ;
      SRAM_ADDR : OUT    std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      SRAM_DQ   : INOUT  std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      SRAM_CE_N : OUT    std_logic ;
      SRAM_OE_N : OUT    std_logic ;
      SRAM_WE_N : OUT    std_logic ;
      SRAM_UB_N : OUT    std_logic ;
      SRAM_LB_N : OUT    std_logic ;
      rd_addr   : IN     std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      rd_en     : IN     std_logic ;
      wr_en     : IN     std_logic ;
      clk       : IN     std_logic ;
      wr_data   : IN     std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      wr_addr   : IN     std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      rd_data   : OUT    std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      RESET_N   : IN     std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : echo_logic USE ENTITY echo_lib.echo_logic;
   FOR ALL : gen_kb_dec USE ENTITY echo_lib.gen_kb_dec;
   FOR ALL : gen_para USE ENTITY echo_lib.gen_para;
   FOR ALL : sram_ctrl USE ENTITY echo_lib.sram_ctrl;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : echo_logic
      GENERIC MAP (
         G_ADDR_WIDTH => 20,         -- physische Adressbreite
         G_DATA_WIDTH => 16
      )
      PORT MAP (
         clk             => clk,
         RESET_N         => RESET_N,
         audio_in_L      => audio_in_L,
         audio_in_R      => audio_in_R,
         audio_out_L     => audio_out_L,
         audio_out_R     => audio_out_R,
         audio_in_ready  => audio_in_ready,
         audio_in_valid  => audio_in_valid,
         audio_out_valid => audio_out_valid,
         wr_en           => wr_en,
         wr_addr         => wr_addr,
         wr_data         => wr_data,
         rd_en           => rd_en,
         rd_addr         => rd_addr,
         rd_valid        => rd_valid,
         rd_data         => rd_data,
         echo_disable    => echo_disable,
         g_feedback_q15  => g_feedback_q15_internal,
         delay_samples   => delay_samples_internal
      );
   U_4 : gen_kb_dec
      GENERIC MAP (
         N       => 6,                                                                               -- Number of functions
         key_map => ("00110011", "00111011", "01000010", "01001011", "00100100", "00000000")         -- Key map provided by user
      )
      PORT MAP (
         clk           => clk,
         scancode      => KB_SCAN_CODE,
         output_signal => ctrl_sig,
         invalid_led   => OPEN
      );
   U_3 : gen_para
      GENERIC MAP (
         fs_hz         => 44100,            -- Sampling frequency
         step_delay_ms => 250,              -- 0,25 s
         step_gain_q15 => 1638              -- ?0,05
      )
      PORT MAP (
         RESET_N        => RESET_N,
         clk            => clk,
         ctrl_sig       => ctrl_sig,
         delay_samples  => delay_samples_internal,
         echo_disable   => echo_disable,
         g_feedback_q15 => g_feedback_q15_internal
      );
   U_1 : sram_ctrl
      GENERIC MAP (
         G_ADDR_WIDTH => 20,
         G_DATA_WIDTH => 16
      )
      PORT MAP (
         rd_valid  => rd_valid,
         SRAM_ADDR => SRAM_ADDR,
         SRAM_DQ   => SRAM_DQ,
         SRAM_CE_N => SRAM_CE_N,
         SRAM_OE_N => SRAM_OE_N,
         SRAM_WE_N => SRAM_WE_N,
         SRAM_UB_N => SRAM_UB_N,
         SRAM_LB_N => SRAM_LB_N,
         rd_addr   => rd_addr,
         rd_en     => rd_en,
         wr_en     => wr_en,
         clk       => clk,
         wr_data   => wr_data,
         wr_addr   => wr_addr,
         rd_data   => rd_data,
         RESET_N   => RESET_N
      );

   -- Implicit buffered output assignments
   delay_samples  <= delay_samples_internal;
   g_feedback_q15 <= g_feedback_q15_internal;

END struct;
