-- VHDL Entity echo_lib.Grp_Nr.generatedInstance
--
-- Created:
--          by - alfth698.student-liu.se (muxen2-103.ad.liu.se)
--          at - 14:48:25 10/17/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY Grp_Nr IS
   PORT( 
      HEX6 : OUT    std_logic;
      HEX7 : OUT    std_logic
   );

END Grp_Nr ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Grp_Nr IS 
BEGIN


END generatedInstance;
