-- VHDL Entity echo_lib.HorizontalBarDisplayGenerator.symbol
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-112.ad.liu.se)
--          at - 11:16:44 10/10/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY HorizontalBarDisplayGenerator IS
   GENERIC( 
      position_x   : integer := 25;
      position_y   : integer := 432;
      width        : integer := 340;
      height       : integer := 48;
      wiper_width  : integer := 12;
      wiper_heigth : integer := 96
   );
   PORT( 
      h_count        : IN     unsigned (10 DOWNTO 0);
      v_count        : IN     unsigned (9 DOWNTO 0);
      wiper_position : IN     unsigned (7 DOWNTO 0);
      mask_f         : OUT    std_logic;
      vga_b          : OUT    std_logic_vector (7 DOWNTO 0);
      vga_g          : OUT    std_logic_vector (7 DOWNTO 0);
      vga_r          : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END HorizontalBarDisplayGenerator ;

--
-- VHDL Architecture echo_lib.HorizontalBarDisplayGenerator.struct
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-112.ad.liu.se)
--          at - 11:16:44 10/10/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
USE IEEE.MATH_REAL.all;

LIBRARY echo_lib;

ARCHITECTURE struct OF HorizontalBarDisplayGenerator IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL b_in_0                : std_logic_vector(7 DOWNTO 0);
   SIGNAL b_in_1                : std_logic_vector(7 DOWNTO 0);
   SIGNAL bar_mask              : std_logic;
   SIGNAL g_in_0                : std_logic_vector(7 DOWNTO 0);
   SIGNAL g_in_1                : std_logic_vector(7 DOWNTO 0);
   SIGNAL r_in_0                : std_logic_vector(7 DOWNTO 0);
   SIGNAL r_in_1                : std_logic_vector(7 DOWNTO 0);
   SIGNAL wiper_center_position : unsigned(10 DOWNTO 0);
   SIGNAL wiper_mask            : std_logic;


   -- Component Declarations
   COMPONENT color_mixer
   PORT (
      b_in_0 : IN     std_logic_vector (7 DOWNTO 0);
      b_in_1 : IN     std_logic_vector (7 DOWNTO 0);
      g_in_0 : IN     std_logic_vector (7 DOWNTO 0);
      g_in_1 : IN     std_logic_vector (7 DOWNTO 0);
      r_in_0 : IN     std_logic_vector (7 DOWNTO 0);
      r_in_1 : IN     std_logic_vector (7 DOWNTO 0);
      sel    : IN     std_logic ;
      b_out  : OUT    std_logic_vector (7 DOWNTO 0);
      g_out  : OUT    std_logic_vector (7 DOWNTO 0);
      r_out  : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT hbar_rasterizer
   GENERIC (
      position_x : INTEGER := 25;
      position_y : INTEGER := 432;
      width      : INTEGER := 340;
      heigth     : INTEGER := 48
   );
   PORT (
      h_count               : IN     unsigned (10 DOWNTO 0);
      v_count               : IN     unsigned (9 DOWNTO 0);
      b_in_0                : OUT    std_logic_vector (7 DOWNTO 0);
      bar_mask              : OUT    std_logic ;
      g_in_0                : OUT    std_logic_vector (7 DOWNTO 0);
      r_in_0                : OUT    std_logic_vector (7 DOWNTO 0);
      wiper_center_position : IN     unsigned (10 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT hbar_wiper_center_position
   GENERIC (
      position_x    : INTEGER := 25;
      width         : INTEGER := 340;
      fixed_comma_p : INTEGER := 3
   );
   PORT (
      h_count               : IN     unsigned (10 DOWNTO 0);
      v_count               : IN     unsigned (9 DOWNTO 0);
      wiper_position        : IN     unsigned (7 DOWNTO 0);
      wiper_center_position : OUT    unsigned (10 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT hbar_wiper_rasterizer
   GENERIC (
      position_x   : INTEGER := 25;
      position_y   : INTEGER := 432;
      wiper_width  : INTEGER := 12;
      wiper_heigth : INTEGER := 96
   );
   PORT (
      h_count               : IN     unsigned (10 DOWNTO 0);
      v_count               : IN     unsigned (9 DOWNTO 0);
      wiper_center_position : IN     unsigned (10 DOWNTO 0);
      b_in_1                : OUT    std_logic_vector (7 DOWNTO 0);
      g_in_1                : OUT    std_logic_vector (7 DOWNTO 0);
      r_in_1                : OUT    std_logic_vector (7 DOWNTO 0);
      wiper_mask            : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : color_mixer USE ENTITY echo_lib.color_mixer;
   FOR ALL : hbar_rasterizer USE ENTITY echo_lib.hbar_rasterizer;
   FOR ALL : hbar_wiper_center_position USE ENTITY echo_lib.hbar_wiper_center_position;
   FOR ALL : hbar_wiper_rasterizer USE ENTITY echo_lib.hbar_wiper_rasterizer;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'or1'
   mask_f <= wiper_mask OR bar_mask;

   -- Instance port mappings.
   U_2 : color_mixer
      PORT MAP (
         b_in_0 => b_in_0,
         b_in_1 => b_in_1,
         g_in_0 => g_in_0,
         g_in_1 => g_in_1,
         r_in_0 => r_in_0,
         r_in_1 => r_in_1,
         sel    => wiper_mask,
         b_out  => vga_b,
         g_out  => vga_g,
         r_out  => vga_r
      );
   U_0 : hbar_rasterizer
      GENERIC MAP (
         position_x => position_x,
         position_y => position_y,
         width      => width,
         heigth     => height
      )
      PORT MAP (
         h_count               => h_count,
         v_count               => v_count,
         b_in_0                => b_in_0,
         bar_mask              => bar_mask,
         g_in_0                => g_in_0,
         r_in_0                => r_in_0,
         wiper_center_position => wiper_center_position
      );
   U_4 : hbar_wiper_center_position
      GENERIC MAP (
         position_x    => position_x,
         width         => width,
         fixed_comma_p => 3
      )
      PORT MAP (
         h_count               => h_count,
         v_count               => v_count,
         wiper_position        => wiper_position,
         wiper_center_position => wiper_center_position
      );
   U_1 : hbar_wiper_rasterizer
      GENERIC MAP (
         position_x   => position_x,
         position_y   => position_y,
         wiper_width  => wiper_width,
         wiper_heigth => wiper_heigth
      )
      PORT MAP (
         h_count               => h_count,
         v_count               => v_count,
         wiper_center_position => wiper_center_position,
         b_in_1                => b_in_1,
         g_in_1                => g_in_1,
         r_in_1                => r_in_1,
         wiper_mask            => wiper_mask
      );

END struct;
