-- VHDL Entity echo_lib.i2c.generatedInstance
--
-- Created:
<<<<<<< HEAD
--          by - antmo328.student-liu.se (muxen2-112.ad.liu.se)
--          at - 22:00:45 10/08/25
=======
--          by - shaha038.student-liu.se (muxen2-108.ad.liu.se)
--          at - 20:23:01 10/17/25
>>>>>>> origin/Shariful
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY i2c IS
END i2c ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF i2c IS 
BEGIN


END generatedInstance;
