-- VHDL Entity echo_lib.top.symbol
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-116.ad.liu.se)
--          at - 16:10:24 10/30/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY top IS
   GENERIC( 
      G_ADDR_WIDTH : natural := 20;      --2^20 x 16 = 2 MB
      G_DATA_WIDTH : natural := 16       --Audio 16-bit
   );
   PORT( 
      AUD_ADCDAT    : IN     std_logic;
      AUD_ADCLRCK   : IN     std_logic;
      AUD_BCLK      : IN     std_logic;
      AUD_DACLRCK   : IN     std_logic;
      fpga_clk      : IN     STD_LOGIC  := '0';
      fpga_reset_n  : IN     std_logic  := '0';
      kb_clk        : IN     std_logic;
      kb_data       : IN     std_logic;
      AUD_DACDAT    : OUT    std_logic;
      AUD_XCK       : OUT    std_logic;
      HEX6          : OUT    std_logic_vector (0 TO 6);
      HEX7          : OUT    std_logic_vector (0 TO 6);
      SCL           : OUT    std_logic;
      SDA           : OUT    std_logic;
      SRAM_ADDR     : OUT    std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      SRAM_CE_N     : OUT    std_logic;
      SRAM_LB_N     : OUT    std_logic;
      SRAM_OE_N     : OUT    std_logic;
      SRAM_UB_N     : OUT    std_logic;
      SRAM_WE_N     : OUT    std_logic;
      audio_debug_1 : OUT    std_logic_vector (7 DOWNTO 0);
      audio_debug_2 : OUT    std_logic_vector (7 DOWNTO 0);
      debug_led_1   : OUT    std_logic;
      debug_led_2   : OUT    std_logic;
      debug_led_3   : OUT    std_logic;
      reduced_clock : OUT    std_logic;
      reset_led     : OUT    std_logic;
      vga_b         : OUT    std_logic_vector (7 DOWNTO 0);
      vga_blank_n   : OUT    std_logic;
      vga_clk       : OUT    std_logic;
      vga_g         : OUT    std_logic_vector (7 DOWNTO 0);
      vga_hsync_n   : OUT    std_logic;
      vga_r         : OUT    std_logic_vector (7 DOWNTO 0);
      vga_sync      : OUT    std_logic;
      vga_vsync_n   : OUT    std_logic;
      SRAM_DQ       : INOUT  std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0)
   );

-- Declarations

END top ;

--
-- VHDL Architecture echo_lib.top.struct
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-116.ad.liu.se)
--          at - 16:10:24 10/30/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY echo_lib;

ARCHITECTURE struct OF top IS

   -- Architecture declarations
   type exemplar_string_array is array (natural range <>, natural range <>) of character;
   attribute pin_number : string;
   attribute array_pin_number : exemplar_string_array;
   
   -- VGA
   attribute pin_number of fpga_clk : signal is "Y2";
   attribute pin_number of fpga_reset_n: signal is "M23";
   attribute pin_number of vga_clk: signal is "A12";
   attribute pin_number of vga_sync: signal is "C10";
   attribute pin_number of vga_blank_n: signal is "F11";
   attribute pin_number of vga_hsync_n: signal is "G13";
   attribute pin_number of vga_vsync_n: signal is "C13";
   attribute array_pin_number of vga_r : signal is ("H10", "H8 ", "J12", "G10", "F12", "D10", "E11", "E12");
   attribute array_pin_number of vga_g : signal is ("C9 ", "F10", "B8 ", "C8 ", "H12", "F8 ", "G11", "G8 ");
   attribute array_pin_number of vga_b : signal is ("D12", "D11", "C12", "A11", "B11", "C11", "A10", "B10");
   
   -- Switches
   -- attribute array_pin_number of left_ear_volume_d : signal is ("AB28", "AC28", "AC27");
   -- attribute array_pin_number of right_ear_volume_d : signal is ("AD27", "AB27", "AC26");
   -- attribute array_pin_number of balance_d : signal is ("AD26", "AB26", "AC25");
   -- attribute array_pin_number of master_volume_d : signal is ("AB25", "AC24", "AB24");
   -- attribute array_pin_number of echo_intensity_d : signal is ("AB23", "AA24", "AA23");
   -- attribute array_pin_number of echo_duration_d : signal is ("AA22", "Y24 ", "Y23 ");
   
   -- SRAM
   attribute array_pin_number of SRAM_ADDR : signal is ("T8  ","AB8 ","AB9 ","AC11","AB11","AA4 ","AC3 ","AB4 ","AD3 ","AF2 ","T7  ","AF5 ","AC5 ","AB5 ", "AE6 ","AB6 ", "AC7 ", "AE7 ","AD7 ","AB7 ");
   attribute array_pin_number of SRAM_DQ : signal is ("AG3 ","AF3 ","AE4 ","AE3 ","AE1 ","AE2 ","AD2 ","AD1 ","AF7 ","AH6 ","AG6 ","AF6 ","AH4 ","AG4 ","AF4 ","AH3 ");
   attribute pin_number of SRAM_CE_N : signal is "AF8";
   attribute pin_number of SRAM_UB_N : signal is "AC4";
   attribute pin_number of SRAM_LB_N : signal is "AD4";
   attribute pin_number of SRAM_OE_N : signal is "AD5";
   attribute pin_number of SRAM_WE_N : signal is "AE8";
   
   -- Audio Codec
   attribute pin_number of AUD_ADCLRCK : signal is "C2";
   attribute pin_number of AUD_ADCDAT: signal is "D2";
   attribute pin_number of AUD_DACLRCK: signal is "E3";
   attribute pin_number of AUD_DACDAT: signal is "D1";
   attribute pin_number of AUD_XCK: signal is "E1";
   attribute pin_number of AUD_BCLK: signal is "F2";
   attribute pin_number of SCL: signal is "B7";
   attribute pin_number of SDA: signal is "A8";
   
   -- Keyboard
   attribute pin_number of kb_clk : signal is "G6";
   attribute pin_number of kb_data : signal is "H5";
   
   -- Seven egment Display
   attribute array_pin_number of hex6 : signal is ("AC17", "AA15", "AB15", "AB17", "AA16", "AB16", "AA17");
   attribute array_pin_number of hex7 : signal is ("AA14", "AG18", "AF17", "AH17", "AG17", "AE17", "AD17");
   
   attribute pin_number of reset_led : signal is "E21";
   attribute pin_number of reduced_clock : signal is "E22";
   
   
   attribute array_pin_number of audio_debug_2 : signal is ("G19", "F19", "E19", "F21", "F18", "E18", "J19", "H19");
   attribute array_pin_number of audio_debug_1 : signal is ("J17", "G17", "J15", "H16", "J16", "H17", "F15", "G15");
   attribute pin_number of debug_led_1 : signal is "G16";
   attribute pin_number of debug_led_2 : signal is "H15";
   attribute pin_number of debug_led_3 : signal is "E25";

   -- Internal signal declarations
   SIGNAL Enable             : std_logic;
   SIGNAL Left_Audio         : std_logic_vector(15 DOWNTO 0);
   SIGNAL Right_Audio        : std_logic_vector(15 DOWNTO 0);
   SIGNAL audio_in_L         : std_logic_vector(G_DATA_WIDTH-1 DOWNTO 0);
   SIGNAL audio_in_R         : std_logic_vector(G_DATA_WIDTH-1 DOWNTO 0);
   SIGNAL audio_in_valid     : std_logic;
   SIGNAL balance_d          : unsigned(7 DOWNTO 0);
   SIGNAL c0                 : STD_LOGIC;
   SIGNAL delay_samples      : std_logic_vector(18 DOWNTO 0);
   SIGNAL dout               : std_logic := '0';
   SIGNAL dout1              : std_logic;
   SIGNAL fpga_reset         : std_logic;
   SIGNAL g_feedback_q16     : std_logic_vector(15 DOWNTO 0);
   SIGNAL left_channel_in    : std_logic_vector(15 DOWNTO 0);
   SIGNAL left_ear_volume_d  : unsigned(7 DOWNTO 0);
   SIGNAL master_volume_d    : unsigned(7 DOWNTO 0);
   SIGNAL right_channel_in   : std_logic_vector(15 DOWNTO 0);
   SIGNAL right_ear_volume_d : unsigned(7 DOWNTO 0);
   SIGNAL scan_code          : std_logic_vector(7 DOWNTO 0);
   SIGNAL u_delay_samples    : unsigned(18 DOWNTO 0);
   SIGNAL u_g_feedback_q16   : unsigned(15 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL AUD_DACDAT_internal    : std_logic;
   SIGNAL reduced_clock_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_18' of 'clkdiv'
   SIGNAL mw_U_18reg_cval : INTEGER RANGE 0 TO 64999999;
   SIGNAL mw_U_18reg_nval : INTEGER RANGE 0 TO 64999999;

   -- ModuleWare signal declarations(v1.12) for instance 'U_19' of 'clkdiv'
   SIGNAL mw_U_19reg_cval : INTEGER RANGE 0 TO 47999;
   SIGNAL mw_U_19reg_nval : INTEGER RANGE 0 TO 47999;

   -- ModuleWare signal declarations(v1.12) for instance 'U_20' of 'clkdiv'
   SIGNAL mw_U_20reg_cval : INTEGER RANGE 0 TO 47999;
   SIGNAL mw_U_20reg_nval : INTEGER RANGE 0 TO 47999;

   -- ModuleWare signal declarations(v1.12) for instance 'U_25' of 'clkdiv'
   SIGNAL mw_U_25reg_cval : INTEGER RANGE 0 TO 3071999;
   SIGNAL mw_U_25reg_nval : INTEGER RANGE 0 TO 3071999;

   -- Component Declarations
   COMPONENT PLL65M
   PORT (
      areset : IN     STD_LOGIC  := '0';
      inclk0 : IN     STD_LOGIC  := '0';
      c0     : OUT    STD_LOGIC;
      locked : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT Vol_BAl
   PORT (
      Enable       : IN     std_logic ;
      Left_Audio   : IN     std_logic_vector (15 DOWNTO 0);
      Reset        : IN     std_logic ;
      Right_Audio  : IN     std_logic_vector (15 DOWNTO 0);
      c0           : IN     std_logic ;
      lrsel        : IN     std_logic ;
      scancode     : IN     std_logic_vector (7 DOWNTO 0);
      Left_Dac     : OUT    std_logic_vector (15 DOWNTO 0);
      Right_Dac    : OUT    std_logic_vector (15 DOWNTO 0);
      signal_ready : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT audio_io
   PORT (
      adc_dat           : IN     std_logic;
      adc_lrc           : IN     std_logic;
      bclk              : IN     std_logic;
      clk               : IN     std_logic;
      dac_lrc           : IN     std_logic;
      data_valid        : IN     std_logic;
      left_channel_out  : IN     std_logic_vector (15 DOWNTO 0);
      reset_n           : IN     std_logic;
      right_channel_out : IN     std_logic_vector (15 DOWNTO 0);
      dac_dat           : OUT    std_logic;
      data_ready        : OUT    std_logic;
      left_channel_in   : OUT    std_logic_vector (15 DOWNTO 0);
      mclk              : OUT    std_logic;
      right_channel_in  : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT echo
   GENERIC (
      G_ADDR_WIDTH    : natural := 20;         --2^20 x 16 = 2 MB
      G_DATA_WIDTH    : natural := 16;         --Audio 16-bit
      G_FS_HZ         : natural := 44100;      --samplerate
      G_GAIN_INIT_Q15 : natural := 9830;       --~0.30 (0.30 * 32768)
      G_GAIN_STEP_Q15 : natural := 512;        --~0.015625 per keyboard use
      G_DELAY_INIT_MS : natural := 1000;       --1.00 s Start
      G_DELAY_STEP_MS : natural := 100         --100 ms per keyboard use
   );
   PORT (
      KB_SCAN_CODE    : IN     std_logic_vector (7 DOWNTO 0);
      RESET_N         : IN     std_logic ;
      audio_in_L      : IN     std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_in_R      : IN     std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_in_valid  : IN     std_logic ;
      clk             : IN     std_logic ;
      SRAM_ADDR       : OUT    std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      SRAM_CE_N       : OUT    std_logic ;
      SRAM_LB_N       : OUT    std_logic ;
      SRAM_OE_N       : OUT    std_logic ;
      SRAM_UB_N       : OUT    std_logic ;
      SRAM_WE_N       : OUT    std_logic ;
      audio_in_ready  : OUT    std_logic ;
      audio_out_L     : OUT    std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_out_R     : OUT    std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0);
      audio_out_valid : OUT    std_logic ;
      delay_samples   : OUT    std_logic_vector (18 DOWNTO 0);
      g_feedback_q15  : OUT    std_logic_vector (15 DOWNTO 0);
      SRAM_DQ         : INOUT  std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT i2c
   PORT (
      SDA   : OUT    std_logic ;
      SCL   : OUT    std_logic ;
      Reset : IN     std_logic ;
      HEX6  : OUT    std_logic_vector (0 TO 6);
      HEX7  : OUT    std_logic_vector (0 TO 6);
      c0    : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT i2s_debug
   PORT (
      AUD_ADCDAT    : IN     std_logic ;
      AUD_BCLK      : IN     std_logic ;
      AUD_DACLRCK   : IN     std_logic ;
      reduced_clock : IN     std_logic ;
      audio_debug_1 : OUT    std_logic_vector (7 DOWNTO 0);
      audio_debug_2 : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT kb_decoder
   PORT (
      kb_clk     : IN     std_logic;
      kb_data    : IN     std_logic;
      sys_clk    : IN     std_logic;
      scan_code  : OUT    std_logic_vector (7 DOWNTO 0);
      scan_ready : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : PLL65M USE ENTITY echo_lib.PLL65M;
   FOR ALL : Vol_BAl USE ENTITY echo_lib.Vol_BAl;
   FOR ALL : audio_io USE ENTITY echo_lib.audio_io;
   FOR ALL : echo USE ENTITY echo_lib.echo;
   FOR ALL : i2c USE ENTITY echo_lib.i2c;
   FOR ALL : i2s_debug USE ENTITY echo_lib.i2s_debug;
   FOR ALL : kb_decoder USE ENTITY echo_lib.kb_decoder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_15' of 'buff'
   u_delay_samples <= unsigned(delay_samples);

   -- ModuleWare code(v1.12) for instance 'U_16' of 'buff'
   u_g_feedback_q16 <= unsigned(g_feedback_q16);

   -- ModuleWare code(v1.12) for instance 'U_17' of 'buff'
   reset_led <= fpga_reset;

   -- ModuleWare code(v1.12) for instance 'U_18' of 'clkdiv'
   u_18drive_proc: PROCESS (mw_U_18reg_cval)
   BEGIN
      IF (mw_U_18reg_cval >= 32500000) THEN
         reduced_clock_internal <= '1';
      ELSE
         reduced_clock_internal <= '0';
      END IF;
   END PROCESS u_18drive_proc;
   u_18clk_in_proc: PROCESS (c0, fpga_reset)
   BEGIN
      IF (fpga_reset = '0') THEN
         mw_U_18reg_cval <= 0;
      ELSIF (c0'EVENT AND c0='1') THEN
         mw_U_18reg_cval <= mw_U_18reg_nval;
      END IF;
   END PROCESS u_18clk_in_proc;
   u_18combo_proc: PROCESS (mw_U_18reg_cval)
   BEGIN
      IF (mw_U_18reg_cval = 64999999) THEN
         mw_U_18reg_nval <= 0;
      ELSE
         mw_U_18reg_nval <= mw_U_18reg_cval + 1;
      END IF;
   END PROCESS u_18combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'clkdiv'
   u_19drive_proc: PROCESS (mw_U_19reg_cval)
   BEGIN
      IF (mw_U_19reg_cval >= 24000) THEN
         debug_led_2 <= '1';
      ELSE
         debug_led_2 <= '0';
      END IF;
   END PROCESS u_19drive_proc;
   u_19clk_in_proc: PROCESS (AUD_DACLRCK, fpga_reset)
   BEGIN
      IF (fpga_reset = '0') THEN
         mw_U_19reg_cval <= 0;
      ELSIF (AUD_DACLRCK'EVENT AND AUD_DACLRCK='1') THEN
         mw_U_19reg_cval <= mw_U_19reg_nval;
      END IF;
   END PROCESS u_19clk_in_proc;
   u_19combo_proc: PROCESS (mw_U_19reg_cval)
   BEGIN
      IF (mw_U_19reg_cval = 47999) THEN
         mw_U_19reg_nval <= 0;
      ELSE
         mw_U_19reg_nval <= mw_U_19reg_cval + 1;
      END IF;
   END PROCESS u_19combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_20' of 'clkdiv'
   u_20drive_proc: PROCESS (mw_U_20reg_cval)
   BEGIN
      IF (mw_U_20reg_cval >= 24000) THEN
         debug_led_1 <= '1';
      ELSE
         debug_led_1 <= '0';
      END IF;
   END PROCESS u_20drive_proc;
   u_20clk_in_proc: PROCESS (AUD_DACDAT_internal, fpga_reset)
   BEGIN
      IF (fpga_reset = '0') THEN
         mw_U_20reg_cval <= 0;
      ELSIF (AUD_DACDAT_internal'EVENT AND AUD_DACDAT_internal='1') THEN
         mw_U_20reg_cval <= mw_U_20reg_nval;
      END IF;
   END PROCESS u_20clk_in_proc;
   u_20combo_proc: PROCESS (mw_U_20reg_cval)
   BEGIN
      IF (mw_U_20reg_cval = 47999) THEN
         mw_U_20reg_nval <= 0;
      ELSE
         mw_U_20reg_nval <= mw_U_20reg_cval + 1;
      END IF;
   END PROCESS u_20combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_25' of 'clkdiv'
   u_25drive_proc: PROCESS (mw_U_25reg_cval)
   BEGIN
      IF (mw_U_25reg_cval >= 1536000) THEN
         debug_led_3 <= '1';
      ELSE
         debug_led_3 <= '0';
      END IF;
   END PROCESS u_25drive_proc;
   u_25clk_in_proc: PROCESS (AUD_BCLK, fpga_reset)
   BEGIN
      IF (fpga_reset = '0') THEN
         mw_U_25reg_cval <= 0;
      ELSIF (AUD_BCLK'EVENT AND AUD_BCLK='1') THEN
         mw_U_25reg_cval <= mw_U_25reg_nval;
      END IF;
   END PROCESS u_25clk_in_proc;
   u_25combo_proc: PROCESS (mw_U_25reg_cval)
   BEGIN
      IF (mw_U_25reg_cval = 3071999) THEN
         mw_U_25reg_nval <= 0;
      ELSE
         mw_U_25reg_nval <= mw_U_25reg_cval + 1;
      END IF;
   END PROCESS u_25combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'gnd'
   master_volume_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_9' of 'gnd'
   Right_Audio <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_10' of 'gnd'
   Left_Audio <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_11' of 'gnd'
   Enable <= '0';

   -- ModuleWare code(v1.12) for instance 'U_12' of 'gnd'
   balance_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_13' of 'gnd'
   right_ear_volume_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_14' of 'gnd'
   left_ear_volume_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_22' of 'gnd'
   audio_in_R <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_23' of 'gnd'
   audio_in_L <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_24' of 'gnd'
   audio_in_valid <= '0';

   -- ModuleWare code(v1.12) for instance 'U_0' of 'inv'
   dout <= NOT(fpga_reset_n);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'vdd'
   dout1 <= '1';

   -- Instance port mappings.
   U_6 : PLL65M
      PORT MAP (
         areset => dout,
         inclk0 => fpga_clk,
         c0     => c0,
         locked => fpga_reset
      );
   U_2 : Vol_BAl
      PORT MAP (
         Enable       => Enable,
         Left_Audio   => Left_Audio,
         Reset        => fpga_reset,
         Right_Audio  => Right_Audio,
         c0           => c0,
         lrsel        => AUD_DACLRCK,
         scancode     => scan_code,
         Left_Dac     => OPEN,
         Right_Dac    => OPEN,
         signal_ready => OPEN
      );
   U_5 : audio_io
      PORT MAP (
         clk               => c0,
         reset_n           => fpga_reset,
         bclk              => AUD_BCLK,
         adc_lrc           => AUD_ADCLRCK,
         dac_lrc           => AUD_DACLRCK,
         adc_dat           => AUD_ADCDAT,
         dac_dat           => AUD_DACDAT_internal,
         mclk              => AUD_XCK,
         left_channel_out  => left_channel_in,
         right_channel_out => right_channel_in,
         left_channel_in   => left_channel_in,
         right_channel_in  => right_channel_in,
         data_ready        => OPEN,
         data_valid        => dout1
      );
   U_1 : echo
      PORT MAP (
         KB_SCAN_CODE    => scan_code,
         RESET_N         => fpga_reset,
         audio_in_L      => audio_in_L,
         audio_in_R      => audio_in_R,
         audio_in_valid  => audio_in_valid,
         clk             => c0,
         SRAM_ADDR       => SRAM_ADDR,
         SRAM_CE_N       => SRAM_CE_N,
         SRAM_LB_N       => SRAM_LB_N,
         SRAM_OE_N       => SRAM_OE_N,
         SRAM_UB_N       => SRAM_UB_N,
         SRAM_WE_N       => SRAM_WE_N,
         audio_in_ready  => OPEN,
         audio_out_L     => OPEN,
         audio_out_R     => OPEN,
         audio_out_valid => OPEN,
         delay_samples   => delay_samples,
         g_feedback_q15  => g_feedback_q16,
         SRAM_DQ         => SRAM_DQ
      );
   U_3 : i2c
      PORT MAP (
         SDA   => SDA,
         SCL   => SCL,
         Reset => fpga_reset,
         HEX6  => HEX6,
         HEX7  => HEX7,
         c0    => c0
      );
   U_21 : i2s_debug
      PORT MAP (
         AUD_ADCDAT    => AUD_ADCDAT,
         AUD_BCLK      => AUD_BCLK,
         AUD_DACLRCK   => AUD_DACLRCK,
         reduced_clock => reduced_clock_internal,
         audio_debug_1 => audio_debug_1,
         audio_debug_2 => audio_debug_2
      );
   U_4 : kb_decoder
      PORT MAP (
         sys_clk    => c0,
         kb_clk     => kb_clk,
         kb_data    => kb_data,
         scan_code  => scan_code,
         scan_ready => OPEN
      );

   -- Implicit buffered output assignments
   AUD_DACDAT    <= AUD_DACDAT_internal;
   reduced_clock <= reduced_clock_internal;

END struct;
