-- VHDL Entity echo_lib.top.symbol
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-116.ad.liu.se)
--          at - 12:19:24 10/30/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY top IS
   GENERIC( 
      G_ADDR_WIDTH : natural := 20;      --2^20 x 16 = 2 MB
      G_DATA_WIDTH : natural := 16       --Audio 16-bit
   );
   PORT( 
      AUD_ADCDAT    : IN     std_logic;
      AUD_ADCLRCK   : IN     std_logic;
      AUD_BCLK      : IN     std_logic;
      AUD_DACLRCK   : IN     std_logic;
      fpga_clk      : IN     STD_LOGIC  := '0';
      fpga_reset_n  : IN     std_logic  := '0';
      kb_clk        : IN     std_logic;
      kb_data       : IN     std_logic;
      AUD_DACDAT    : OUT    std_logic;
      AUD_XCK       : OUT    std_logic;
      HEX6          : OUT    std_logic_vector (0 TO 6);
      HEX7          : OUT    std_logic_vector (0 TO 6);
      SCL           : OUT    std_logic;
      SDA           : OUT    std_logic;
      SRAM_ADDR     : OUT    std_logic_vector (G_ADDR_WIDTH-1 DOWNTO 0);
      SRAM_CE_N     : OUT    std_logic;
      SRAM_LB_N     : OUT    std_logic;
      SRAM_OE_N     : OUT    std_logic;
      SRAM_UB_N     : OUT    std_logic;
      SRAM_WE_N     : OUT    std_logic;
      audio_debug   : OUT    std_logic_vector (7 DOWNTO 0);
      reduced_clock : OUT    std_logic;
      reset_led     : OUT    std_logic;
      scan_code     : OUT    std_logic_vector (7 DOWNTO 0);
      vga_b         : OUT    std_logic_vector (7 DOWNTO 0);
      vga_blank_n   : OUT    std_logic;
      vga_clk       : OUT    std_logic;
      vga_g         : OUT    std_logic_vector (7 DOWNTO 0);
      vga_hsync_n   : OUT    std_logic;
      vga_r         : OUT    std_logic_vector (7 DOWNTO 0);
      vga_sync      : OUT    std_logic;
      vga_vsync_n   : OUT    std_logic;
      SRAM_DQ       : INOUT  std_logic_vector (G_DATA_WIDTH-1 DOWNTO 0)
   );

-- Declarations

END top ;

--
-- VHDL Architecture echo_lib.top.debug_vga
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-116.ad.liu.se)
--          at - 12:37:53 10/30/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY echo_lib;

ARCHITECTURE debug_vga OF top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL balance_d          : unsigned(7 DOWNTO 0);
   SIGNAL echo_duration_d    : unsigned(7 DOWNTO 0);
   SIGNAL echo_intensity_d   : unsigned(7 DOWNTO 0);
   SIGNAL left_ear_volume_d  : unsigned(7 DOWNTO 0);
   SIGNAL master_volume_d    : unsigned(7 DOWNTO 0);
   SIGNAL right_ear_volume_d : unsigned(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT vga
   PORT (
      balance_d          : IN     unsigned (7 DOWNTO 0);
      c0                 : IN     std_logic ;
      echo_duration_d    : IN     unsigned (7 DOWNTO 0);
      echo_intensity_d   : IN     unsigned (7 DOWNTO 0);
      fpga_reset_n       : IN     std_logic ;
      left_ear_volume_d  : IN     unsigned (7 DOWNTO 0);
      master_volume_d    : IN     unsigned (7 DOWNTO 0);
      right_ear_volume_d : IN     unsigned (7 DOWNTO 0);
      vga_b              : OUT    std_logic_vector (7 DOWNTO 0);
      vga_blank_n        : OUT    std_logic ;
      vga_clk            : OUT    std_logic ;
      vga_g              : OUT    std_logic_vector (7 DOWNTO 0);
      vga_hsync_n        : OUT    std_logic ;
      vga_r              : OUT    std_logic_vector (7 DOWNTO 0);
      vga_sync           : OUT    std_logic ;
      vga_vsync_n        : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : vga USE ENTITY echo_lib.vga;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'gnd'
   balance_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_2' of 'gnd'
   echo_duration_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_3' of 'gnd'
   echo_intensity_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_4' of 'gnd'
   left_ear_volume_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_5' of 'gnd'
   master_volume_d <= (OTHERS => '0');

   -- ModuleWare code(v1.12) for instance 'U_6' of 'gnd'
   right_ear_volume_d <= (OTHERS => '0');

   -- Instance port mappings.
   U_0 : vga
      PORT MAP (
         balance_d          => balance_d,
         c0                 => fpga_clk,
         echo_duration_d    => echo_duration_d,
         echo_intensity_d   => echo_intensity_d,
         fpga_reset_n       => fpga_reset_n,
         left_ear_volume_d  => left_ear_volume_d,
         master_volume_d    => master_volume_d,
         right_ear_volume_d => right_ear_volume_d,
         vga_b              => vga_b,
         vga_blank_n        => vga_blank_n,
         vga_clk            => vga_clk,
         vga_g              => vga_g,
         vga_hsync_n        => vga_hsync_n,
         vga_r              => vga_r,
         vga_sync           => vga_sync,
         vga_vsync_n        => vga_vsync_n
      );

END debug_vga;
