-- VHDL Entity echo_lib.vga.interface
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-112.ad.liu.se)
--          at - 09:01:58 10/07/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY vga IS
   PORT( 
      balance          : IN     unsigned (7 DOWNTO 0);
      echo_duration    : IN     unsigned (7 DOWNTO 0);
      echo_intensity   : IN     unsigned (7 DOWNTO 0);
      fpga_clk         : IN     STD_LOGIC  := '0';
      fpga_reset_n     : IN     std_logic;
      left_ear_volume  : IN     unsigned (7 DOWNTO 0);
      master_volume    : IN     unsigned (7 DOWNTO 0);
      right_ear_volume : IN     unsigned (7 DOWNTO 0);
      vga_b            : OUT    std_logic_vector (7 DOWNTO 0);
      vga_blank_n      : OUT    std_logic;
      vga_clk          : OUT    std_logic;
      vga_g            : OUT    std_logic_vector (7 DOWNTO 0);
      vga_hsync_n      : OUT    std_logic;
      vga_r            : OUT    std_logic_vector (7 DOWNTO 0);
      vga_sync         : OUT    std_logic;
      vga_vsync_n      : OUT    std_logic
   );

-- Declarations

END vga ;

--
-- VHDL Architecture echo_lib.vga.struct
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-112.ad.liu.se)
--          at - 09:01:58 10/07/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY altera_mf;
USE altera_mf.all;

LIBRARY echo_lib;

ARCHITECTURE struct OF vga IS

   -- Architecture declarations
   type exemplar_string_array is array (natural range <>, natural range <>) of character;
   attribute pin_number : string;
   attribute array_pin_number : exemplar_string_array;
   
   -- VGA
   attribute pin_number of fpga_clk : signal is "Y2";
   attribute pin_number of fpga_reset_n: signal is "M23";
   attribute pin_number of vga_clk: signal is "A12";
   attribute pin_number of vga_sync: signal is "C10";
   attribute pin_number of vga_blank_n: signal is "F11";
   attribute pin_number of vga_hsync_n: signal is "G13";
   attribute pin_number of vga_vsync_n: signal is "C13";
   attribute array_pin_number of vga_r : signal is ("H10", "H8 ", "J12", "G10", "F12", "D10", "E11", "E12");
   attribute array_pin_number of vga_g : signal is ("C9 ", "F10", "B8 ", "C8 ", "H12", "F8 ", "G11", "G8 ");
   attribute array_pin_number of vga_b : signal is ("D12", "D11", "C12", "A11", "B11", "C11", "A10", "B10");
   
   -- Switches
   attribute array_pin_number of left_ear_volume : signal is ("AB28", "AC28", "AC27", "AD27", "AB27", "AC26", "AD26", "AB26");
   attribute array_pin_number of right_ear_volume : signal is ("AC25", "AB25", "AC24", "AB24", "AB23", "AA24", "AA23", "AA22");

   -- Internal signal declarations
   SIGNAL c0      : std_logic;
   SIGNAL dout    : std_logic;
   SIGNAL h_count : unsigned(10 DOWNTO 0);
   SIGNAL hblank  : std_logic;
   SIGNAL v_count : unsigned(9 DOWNTO 0);
   SIGNAL vblank  : std_logic;


   -- Component Declarations
   COMPONENT PLL65M
   PORT (
      areset : IN     STD_LOGIC  := '0';
      inclk0 : IN     STD_LOGIC  := '0';
      c0     : OUT    STD_LOGIC;
      locked : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT h_syncr
   PORT (
      c0           : IN     std_logic ;
      fpga_reset_n : IN     std_logic ;
      h_count      : IN     unsigned (10 DOWNTO 0);
      hblank       : OUT    std_logic ;
      vga_hsync_n  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT line_counter
   PORT (
      c0           : IN     std_logic ;
      fpga_reset_n : IN     std_logic ;
      h_count      : IN     unsigned (10 DOWNTO 0);
      v_count      : OUT    unsigned (9 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT pixel_color_generator
   PORT (
      balance          : IN     unsigned (7 DOWNTO 0);
      c0               : IN     std_logic ;
      echo_duration    : IN     unsigned (7 DOWNTO 0);
      echo_intensity   : IN     unsigned (7 DOWNTO 0);
      fpga_reset_n     : IN     std_logic ;
      h_count          : IN     unsigned (10 DOWNTO 0);
      left_ear_volume  : IN     unsigned (7 DOWNTO 0);
      master_volume    : IN     unsigned (7 DOWNTO 0);
      right_ear_volume : IN     unsigned (7 DOWNTO 0);
      v_count          : IN     unsigned (9 DOWNTO 0);
      vga_b            : OUT    std_logic_vector (7 DOWNTO 0);
      vga_g            : OUT    std_logic_vector (7 DOWNTO 0);
      vga_r            : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT pixel_counter
   PORT (
      c0           : IN     std_logic ;
      fpga_reset_n : IN     std_logic ;
      h_count      : OUT    unsigned (10 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT v_syncr
   PORT (
      c0           : IN     std_logic ;
      fpga_reset_n : IN     std_logic ;
      v_count      : IN     unsigned (9 DOWNTO 0);
      vblank       : OUT    std_logic ;
      vga_vsync_n  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : PLL65M USE ENTITY echo_lib.PLL65M;
   FOR ALL : h_syncr USE ENTITY echo_lib.h_syncr;
   FOR ALL : line_counter USE ENTITY echo_lib.line_counter;
   FOR ALL : pixel_color_generator USE ENTITY echo_lib.pixel_color_generator;
   FOR ALL : pixel_counter USE ENTITY echo_lib.pixel_counter;
   FOR ALL : v_syncr USE ENTITY echo_lib.v_syncr;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_6' of 'gnd'
   vga_sync <= '0';

   -- ModuleWare code(v1.12) for instance 'U_9' of 'gnd'
   dout <= '0';

   -- ModuleWare code(v1.12) for instance 'U_7' of 'inv'
   vga_clk <= NOT(c0);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'nor'
   vga_blank_n <= NOT(hblank OR vblank);

   -- Instance port mappings.
   U_8 : PLL65M
      PORT MAP (
         areset => dout,
         inclk0 => fpga_clk,
         c0     => c0,
         locked => OPEN
      );
   U_3 : h_syncr
      PORT MAP (
         c0           => c0,
         fpga_reset_n => fpga_reset_n,
         h_count      => h_count,
         hblank       => hblank,
         vga_hsync_n  => vga_hsync_n
      );
   U_2 : line_counter
      PORT MAP (
         c0           => c0,
         fpga_reset_n => fpga_reset_n,
         h_count      => h_count,
         v_count      => v_count
      );
   U_0 : pixel_color_generator
      PORT MAP (
         balance          => balance,
         c0               => c0,
         echo_duration    => echo_duration,
         echo_intensity   => echo_intensity,
         fpga_reset_n     => fpga_reset_n,
         h_count          => h_count,
         left_ear_volume  => left_ear_volume,
         master_volume    => master_volume,
         right_ear_volume => right_ear_volume,
         v_count          => v_count,
         vga_b            => vga_b,
         vga_g            => vga_g,
         vga_r            => vga_r
      );
   U_1 : pixel_counter
      PORT MAP (
         c0           => c0,
         fpga_reset_n => fpga_reset_n,
         h_count      => h_count
      );
   U_4 : v_syncr
      PORT MAP (
         c0           => c0,
         fpga_reset_n => fpga_reset_n,
         v_count      => v_count,
         vblank       => vblank,
         vga_vsync_n  => vga_vsync_n
      );

END struct;
