-- VHDL Entity echo_lib.vga.generatedInstance
--
-- Created:
--          by - alfth698.student-liu.se (muxen2-108.ad.liu.se)
--          at - 14:10:50 10/13/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY vga IS
END vga ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF vga IS 
BEGIN


END generatedInstance;
