-- VHDL Entity echo_lib.vol_bal.generatedInstance
--
-- Created:
--          by - ramku837.student-liu.se (muxen2-101.ad.liu.se)
--          at - 10:28:43 10/30/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY vol_bal IS
END vol_bal ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF vol_bal IS 
BEGIN


END generatedInstance;
