-- VHDL Entity echo_lib.wiper_generator.interface
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-109.ad.liu.se)
--          at - 19:06:59 10/14/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY echo_lib;
USE echo_lib.color_t.ALL;
USE IEEE.MATH_REAL.all;

ENTITY wiper_generator IS
   GENERIC( 
      minor_radius    : integer := 44;
      major_radius    : integer := 84;
      angle_amplitude : integer := 270;
      center_angle    : integer := 90;
      center_x        : integer := 195;
      center_y        : integer := 197;
      tap_width       : integer := 24;
      tap_height      : integer := 48
   );
   PORT( 
      angle       : IN     unsigned (7 DOWNTO 0);
      c0          : IN     std_logic;
      h_count     : IN     unsigned (10 DOWNTO 0);
      v_count     : IN     unsigned (9 DOWNTO 0);
      wiper_color : OUT    rgb_color_t;
      wiper_mask  : OUT    std_logic
   );

-- Declarations

END wiper_generator ;

--
-- VHDL Architecture echo_lib.wiper_generator.struct
--
-- Created:
--          by - leoag319.student-liu.se (muxen2-109.ad.liu.se)
--          at - 19:16:15 10/14/25
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 18:06:06
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY echo_lib;
USE echo_lib.color_t.ALL;


ARCHITECTURE struct OF wiper_generator IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Ax : unsigned(10 DOWNTO 0);
   SIGNAL Ay : unsigned(9 DOWNTO 0);
   SIGNAL Bx : unsigned(10 DOWNTO 0);
   SIGNAL By : unsigned(9 DOWNTO 0);
   SIGNAL Cx : unsigned(10 DOWNTO 0);
   SIGNAL Cy : unsigned(9 DOWNTO 0);
   SIGNAL Dx : unsigned(10 DOWNTO 0);
   SIGNAL Dy : unsigned(9 DOWNTO 0);


   -- Component Declarations
   COMPONENT pipelined_wiper_rasterizer
   PORT (
      Ax          : IN     unsigned (10 DOWNTO 0);
      Ay          : IN     unsigned (9 DOWNTO 0);
      Bx          : IN     unsigned (10 DOWNTO 0);
      By          : IN     unsigned (9 DOWNTO 0);
      Cx          : IN     unsigned (10 DOWNTO 0);
      Cy          : IN     unsigned (9 DOWNTO 0);
      Dx          : IN     unsigned (10 DOWNTO 0);
      Dy          : IN     unsigned (9 DOWNTO 0);
      c0          : IN     std_logic;
      h_count     : IN     unsigned (10 DOWNTO 0);
      v_count     : IN     unsigned (9 DOWNTO 0);
      wiper_color : OUT    rgb_color_t;
      wiper_mask  : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT point_computation
   GENERIC (
      minor_radius    : integer := 44;       -- 
      major_radius    : integer := 84;       -- 
      angle_amplitude : integer := 270;      -- 
      center_angle    : integer := 90;       -- 
      center_x        : integer := 195;      -- 
      center_y        : integer := 197;      -- 
      tap_width       : integer := 24;       -- 
      tap_height      : integer := 48        -- 
   );
   PORT (
      angle   : IN     unsigned (7 DOWNTO 0);
      c0      : IN     std_logic ;
      v_count : IN     unsigned (9 DOWNTO 0);
      Ax      : OUT    unsigned (10 DOWNTO 0);
      Ay      : OUT    unsigned (9 DOWNTO 0);
      Bx      : OUT    unsigned (10 DOWNTO 0);
      By      : OUT    unsigned (9 DOWNTO 0);
      Cx      : OUT    unsigned (10 DOWNTO 0);
      Cy      : OUT    unsigned (9 DOWNTO 0);
      Dx      : OUT    unsigned (10 DOWNTO 0);
      Dy      : OUT    unsigned (9 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : pipelined_wiper_rasterizer USE ENTITY echo_lib.pipelined_wiper_rasterizer;
   FOR ALL : point_computation USE ENTITY echo_lib.point_computation;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : pipelined_wiper_rasterizer
      PORT MAP (
         Ax          => Ax,
         Ay          => Ay,
         Bx          => Bx,
         By          => By,
         Cx          => Cx,
         Cy          => Cy,
         Dx          => Dx,
         Dy          => Dy,
         c0          => c0,
         h_count     => h_count,
         v_count     => v_count,
         wiper_color => wiper_color,
         wiper_mask  => wiper_mask
      );
   U_1 : point_computation
      PORT MAP (
         angle   => angle,
         c0      => c0,
         v_count => v_count,
         Ax      => Ax,
         Ay      => Ay,
         Bx      => Bx,
         By      => By,
         Cx      => Cx,
         Cy      => Cy,
         Dx      => Dx,
         Dy      => Dy
      );

END struct;
